require 'fileutils'
require 'front_matter_parser'
require 'json'
require 'time'
require 'tmpdir'

module XAeonAgentsSkills

  # Cline Ruby connector
  class Cline

    # Constructor
    #
    # Parameters::
    # * *api_key* (String): The Cline API key
    # * *debug* (Boolean): Do we activate debug mode? [default: false]
    def initialize(api_key, debug: false)
      @api_key = api_key
      @debug = debug
    end

    # Send a prompt to a Cline agent
    #
    # Parameters::
    # * *json_prompt* (Object): Prompt to be sent, as a JSON object (could be Hash, Array, Integer, String...)
    # * *model* (String): Cline model to be used
    # * *config* (Hash): Cline config [default: {}]
    # * *skills* (Array<String>): List of skills to activate for this prompt [default: []]
    # * *skillkit_agents* (Boolean): Is AGENTS.md generated by skillkit? If true then a temporary AGENTS.md file will be used to deactivate non-desired skills. [default: false]
    # * *cli_args* (String): Additional CLI arguments [default: '']
    # * *on_message* (Proc or nil): Callback to be called everytime a new message happens in the task being executed, or nil if no callback [default: nil]
    #   * Parameters::
    #     * *message* (Hash): Message that has happened
    def prompt(json_prompt, model:, config: {}, skills: [], skillkit_agents: false, cli_args: '', on_message: nil)
      with_temp_dir do |temp_dir|
        config_dir = "#{temp_dir}/cline_config"
        log_debug "Temporary Cline config dir: #{config_dir}"

        # Authenticate and generate the configuration directory
        system "cline auth --config #{config_dir} --provider cline --apikey #{@api_key} --modelid #{model}", exception: true
        log_debug 'Cline CLI authenticated successfully'

        # Merge configuration options from payload into the globalState.json file
        global_state_path = "#{config_dir}/data/globalState.json"
        File.write(
          global_state_path,
          JSON.pretty_generate(
            Helpers.deep_merge(
              JSON.parse(File.read(global_state_path)),
              config
            )
          )
        )

        # Generate prompt
        prompt_file = "#{temp_dir}/prompt.json"
        File.write(prompt_file, JSON.pretty_generate(json_prompt))

        with_selected_skills(skills, config_dir:, skillkit_agents:) do
          with_messages_monitoring(config_dir:, on_message:) do
            # Run the agent
            cmd = "cline --config #{config_dir} --act #{@debug ? '--verbose' : ''} --json #{cli_args} < #{prompt_file}"
            log_debug "Cline CLI: #{cmd}"
            XAeonAgentsSkills::Helpers.run_cmd(
              cmd,
              debug: @debug,
              on_stdout: proc { |line| log_debug line },
              on_stderr: proc { |line| $stderr.puts line }
            )
          end
        end
      end
    end

    private

    # Monitor messages arriving for a task and call a callback for each one of them.
    #
    # Parameters::
    # * *config_dir* (String): Configuration from which the task should be found
    # * *on_message* (Proc or nil): Callback to be called everytime a new message happens in the task being executed, or nil if no callback
    #   * Parameters::
    #     * *message* (Hash): Message that has happened
    # * Proc: Code called with monitoring in place
    def with_messages_monitoring(config_dir:, on_message:)
      if on_message.nil?
        yield
      else
        monitoring = true
        monitoring_thread = Thread.new do
          ui_messages_file = nil
          ui_messages_file_mtime = nil
          ui_messages_file_last_ts = 0
          while monitoring
            ui_messages_file = Dir["#{config_dir}/data/tasks/*/ui_messages.json"].first if ui_messages_file.nil?
            unless ui_messages_file.nil?
              new_ui_messages_file_mtime = File.mtime(ui_messages_file)
              if new_ui_messages_file_mtime != ui_messages_file_mtime
                # New messages have been added
                new_messages = JSON.parse(File.read(ui_messages_file), symbolize_names: true).select { |message| message[:ts] > ui_messages_file_last_ts }
                unless new_messages.empty?
                  new_messages.each { |message| on_message.call(message) }
                  ui_messages_file_last_ts = new_messages.last[:ts]
                end
                ui_messages_file_mtime = new_ui_messages_file_mtime
              end
            end
            sleep 1
          end
        end
        begin
          yield
        ensure
          monitoring = false
          monitoring_thread.join
        end
      end
    end

    # Call some code with Cline configured to run only with some selected skills.
    # This requires to generate the config file with all other skills to be disabled.
    # In case of skillkit usage, it also requires to alter the AGENTS.md file by generating another temporary one.
    #
    # Parameters::
    # * *skills* (Array<String>): List of skills to activate for this prompt
    # * *config_dir* (String): Configuration directory
    # * *skillkit_agents* (Boolean): Is AGENTS.md generated by skillkit? If true then a temporary AGENTS.md file will be used to deactivate non-desired skills. [default: false]
    # * Proc: Code called with skills setup properly
    def with_selected_skills(skills, config_dir:, skillkit_agents: false)
      # Select the skills to be hidden, so that only the selected ones are available to our agent
      selected_skills = skills.dup
      skills.each do |skill|
        dependent_skills(skill, selected_skills)
      end
      log_debug "#{selected_skills.size} selected skills: #{selected_skills.join(', ')}"
      all_skills = Dir['.cline/skills/*'].map { |skill_dir| File.basename(skill_dir) }
      missing_skills = selected_skills - all_skills
      raise "#{missing_skills.size} missing skills: #{missing_skills.join(', ')}" unless missing_skills.empty?
      hidden_skills = all_skills - selected_skills
      log_debug "#{hidden_skills.size} skills to disable: #{hidden_skills.join(', ')}"

      # Set the workspace config, dealing with disabled rules and skills
      workspace_config = {
        localSkillsToggles: hidden_skills.to_h do |skill|
          [
            canonize_path(".cline/skills/#{skill}/SKILL.md"),
            false
          ]
        end
      }

      temp_agents_file = nil
      if skillkit_agents
        # We have to replace the AGENTS.md file with another version that is specific to this run and only has the selected skills.
        temp_agents_file = ".clinerules/x-aeon-agents/AGENTS-#{unique_id { |id| !File.exist?(".clinerules/x-aeon-agents/AGENTS-#{id}.md") }}.md"
        agents_content = File.read('AGENTS.md')
        hidden_skills.each do |skill|
          escaped_skill = Regexp.escape(skill)
          agents_content.gsub!(/- \*\*#{escaped_skill}\*\*: [^\n]+\n/, '')
          agents_content.gsub!(/<skill>\n<name>#{escaped_skill}<\/name>.+?<\/skill>\n\n/m, '')
        end
        # Alter the workspace config accordingly to use this temporary AGENTS.md file
        workspace_config.merge!(
          localClineRulesToggles: {
            canonize_path(temp_agents_file) => true
          },
          localAgentsRulesToggles: {
            canonize_path('AGENTS.md') => false
          }
        )
        # Create the temporary AGENTS.md file
        FileUtils.mkdir_p File.dirname(temp_agents_file)
        File.write(temp_agents_file, agents_content)
      end

      begin
        # Create the workspace configuration file
        File.write(
          "#{Dir["#{config_dir}/data/workspaces/*"].first}/workspaceState.json",
          JSON.pretty_generate(workspace_config)
        )
        yield
      ensure
        FileUtils.rm_f(temp_agents_file) unless temp_agents_file.nil?
      end
    end

    # Get a full file path as Cline config file is expecting it
    #
    # Parameters::
    # * *path* (String): A file path
    # Result::
    # * String: The corresponding file path that can be included in Cline config files
    def canonize_path(path)
      File.expand_path(path).gsub(File::SEPARATOR, File::ALT_SEPARATOR || File::SEPARATOR)
    end

    # Log a message if debug was activated
    #
    # Parameters::
    # * *msg* (String): Message to be displayed
    def log_debug(msg)
      puts "[DEBUG] - #{msg}" if @debug
    end

    # Setup a temporary directory.
    # In case of debug activated, create the temporary directory from the current one and don't delete it.
    #
    # Parameters::
    # * *block* (Proc): Code called with the temp dir created
    #   * Parameters::
    #     * *temp_dir* (String): The temporary directory
    def with_temp_dir(&block)
      if @debug
        temp_dir = "tmp/cline/#{unique_id { |id| !File.exist?("tmp/cline/#{id}") }}"
        FileUtils.mkdir_p temp_dir
        block.call(temp_dir)
      else
        Dir.mktmpdir(&block)
      end
    end

    # Find a unique ID, with a client code block validating its unicity.
    #
    # Parameters::
    # * Proc: Code validating unicity
    #   * Parameters::
    #     * *id* (String): ID to validate the unicity of
    #   * Result::
    #     * Boolean: Is the ID unique?
    def unique_id
      id = nil
      unique_idx = 0
      loop do
        id = "#{Time.now.strftime('%Y-%m-%d-%H-%M-%S')}-#{unique_idx}"
        break if yield(id)
        unique_idx += 1
      end
      id
    end

    # Get all skills dependencies recursively from a skill.
    # Handle cyclic dependencies.
    #
    # Parameters::
    # * *skill* (String): Skill
    # * *found_skills* (Array<String>): In place array of skills that have already been found as dependencies
    def dependent_skills(skill, found_skills)
      deps = FrontMatterParser::Parser.parse_file(".cline/skills/#{skill}/SKILL.md").front_matter.dig('metadata', 'dependencies')
      unless deps.nil?
        deps.each do |skill_dep|
          skill_dep_name = skill_dep.include?(':') ? skill_dep.match(/^[^:]+:(.+)$/)[1] : skill_dep
          unless found_skills.include?(skill_dep_name)
            found_skills << skill_dep_name
            dependent_skills(skill_dep_name, found_skills)
          end
        end
      end
    end

  end

end
